name: Deploy With Docker to AWS Server
# 실행 조건
on:
  push:
    # main으로 commit & push인 경우 
    branches:
      - main #main commit and push = [main,master]
jobs:
  deploy:
    # Github Actions가 제공하는 Ubuntu환경에서 실행
    # AWS EC2가 아니고 Github Actions 임시로 사용하는 Ubuntu
    runs-on: ubuntu-latest
    #  실행 순서 지정 
    #  name = stage = step
    steps:
     # 어떤 소스를 가지고 올지 => src / build.grade gradlew Dockerfile
     - name: Checkout:repository
       uses: actions/checkout@v4
     # JDK 설정 => SpringBoot프로젝트를 build => JDK 설정 
     - name: SetUp JDK 21
       uses: actions/setup-java@v4
       with:
         # 가장 최소단위 JDK = 이클립스 JDK 사용
         distribution: 'temurin'
         java-version: '21'
     # 환경 설정 
     
     # Gradlew 권한 부여 
     - name: Set gradlew permission
       run: |
         chmod +x ./gradlew
     # Gradle Build 
     - name: Build with Gradlew
       run: ./gradlew clean build -x test
     # Docker Hub 연결 = 로그인 
     - name: Login DockerHub
       run: |
         echo "${{secrets.DOCKER_PASSWORD}}" |\
         docker login \
         -u "${{secrets.DOCKER_USERNAME}}" \
         --password-stdin
     # Docker 이미지 생성 
     - name: Build Docker Image 
       run: |
         docker build \
          -t ${{secrets.DOCKER_USERNAME}}/last-app:latest .
     # DockerHub에 올린다 
     - name: Push Docker Image 
       run: |
         docker push \
          ${{secrets.DOCKER_USERNAME}}/last-app:latest
     # AWS 연결 => DockerHub 데이터  Pull
     - name: Set SSH key Permission
       run: |
         mkdir -p ~/.ssh
         echo "${{secrets.SERVER_SSH_KEY}}" > ~/.ssh/id_ed25519
         chmod 600 ~/.ssh/id_ed25519
     # ADD SSH Key 
     - name: Add SSH Key 
       uses: webfactory/ssh-agent@v0.5.3
       with:
         ssh-private-key: ${{secrets.SERVER_SSH_KEY}}
     # Add Known_hosts
     - name: Add Known_hosts
       run: |
         ssh-keyscan -H 13.124.133.9 >> ~/.ssh/known_hosts
    # DB관련 => .env 
     - name: 환경설정
       run: |
          ssh ubuntu@13.124.133.9 << EOF
           # 기존의 파일 삭제
           mkdir -p ~/app
           cd ~/app
           rm -f .env
           
           echo "DB_URL=${{secrets.DB_URL}}" >> ~/app/.env
           echo "DB_USERNAME=${{secrets.DB_USERNAME}}" >> ~/app/.env
           echo "DB_PASSWORD=${{secrets.DB_PASSWORD}}" >> ~/app/.env
           chmod 600 ~/app/.env
          EOF
     - name: SCP docker-compose
       run: |
         ssh ubuntu@13.124.133.9 "mkdir -p /home/ubuntu/app"
         scp docker-compose.yml ubuntu@13.124.133.9:/home/ubuntu/app/docker-compose.yml
    
     # Deploy on service DockerHub Image using
     - name: DockerHub Image using
       run: |
         ssh ubuntu@13.124.133.9 << 'EOF'
          cd /home/ubuntu/app
          docker-compose pull
          docker-compose down
          docker-compose up -d
         EOF
